// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	email.proto

It has these top-level messages:
	EmailSendSingleReq
	EmailSendSingleResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailSendSingleReq struct {
	Email      string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	VerifyCode string `protobuf:"bytes,2,opt,name=verify_code" json:"verify_code,omitempty"`
}

func (m *EmailSendSingleReq) Reset()                    { *m = EmailSendSingleReq{} }
func (m *EmailSendSingleReq) String() string            { return proto.CompactTextString(m) }
func (*EmailSendSingleReq) ProtoMessage()               {}
func (*EmailSendSingleReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmailSendSingleReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailSendSingleReq) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

type EmailSendSingleResp struct {
}

func (m *EmailSendSingleResp) Reset()                    { *m = EmailSendSingleResp{} }
func (m *EmailSendSingleResp) String() string            { return proto.CompactTextString(m) }
func (*EmailSendSingleResp) ProtoMessage()               {}
func (*EmailSendSingleResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*EmailSendSingleReq)(nil), "pb.EmailSendSingleReq")
	proto.RegisterType((*EmailSendSingleResp)(nil), "pb.EmailSendSingleResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Email service

type EmailClient interface {
	SendSignupVerifyCode(ctx context.Context, in *EmailSendSingleReq, opts ...grpc.CallOption) (*EmailSendSingleResp, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) SendSignupVerifyCode(ctx context.Context, in *EmailSendSingleReq, opts ...grpc.CallOption) (*EmailSendSingleResp, error) {
	out := new(EmailSendSingleResp)
	err := grpc.Invoke(ctx, "/pb.Email/SendSignupVerifyCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Email service

type EmailServer interface {
	SendSignupVerifyCode(context.Context, *EmailSendSingleReq) (*EmailSendSingleResp, error)
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_SendSignupVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailSendSingleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SendSignupVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Email/SendSignupVerifyCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SendSignupVerifyCode(ctx, req.(*EmailSendSingleReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSignupVerifyCode",
			Handler:    _Email_SendSignupVerifyCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}

func init() { proto.RegisterFile("email.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x4d, 0xcc,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe0, 0x12, 0x72,
	0x05, 0x09, 0x05, 0xa7, 0xe6, 0xa5, 0x04, 0x67, 0xe6, 0xa5, 0xe7, 0xa4, 0x06, 0xa5, 0x16, 0x0a,
	0xf1, 0x72, 0xb1, 0x82, 0x15, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x0a, 0x09, 0x73, 0x71, 0x97,
	0xa5, 0x16, 0x65, 0xa6, 0x55, 0xc6, 0x27, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x81, 0x04, 0x95, 0x44,
	0xb9, 0x84, 0x31, 0x74, 0x16, 0x17, 0x18, 0x05, 0x71, 0xb1, 0x82, 0x85, 0x85, 0x3c, 0xb9, 0x44,
	0x20, 0x52, 0xe9, 0x79, 0xa5, 0x05, 0x61, 0x60, 0xed, 0xce, 0xf9, 0x29, 0xa9, 0x42, 0x62, 0x7a,
	0x05, 0x49, 0x7a, 0x98, 0x76, 0x4a, 0x89, 0x63, 0x15, 0x2f, 0x2e, 0x50, 0x62, 0x48, 0x62, 0x03,
	0xbb, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x88, 0xe8, 0xf6, 0x87, 0xbe, 0x00, 0x00, 0x00,
}
